version: '4'
services: 
  mysql:
    image: mysql:8.3.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASWORD: mysql
    ports:
      - "3006:3006"
    volumes:
      - ./mysql:/var/lib/mysql